### ISSUE TITLE
Have Issue Error detected - status code 2

### ISSUE THREAD

**Issue by rsun-thoughtworks** [fidian/aws-resource-list#1]
./aws-resource-list --parallel=20
Account ID:	xxx
Alias:
Regions:	global,ap-northeast-1,ap-northeast-2,ap-south-1,ap-southeast-1,ap-southeast-2,ca-central-1,eu-central-1,eu-north-1,eu-west-1,eu-west-2,eu-west-3,sa-east-1,us-east-1,us-east-2,us-west-1,us-west-2
Error detected - status code 2
Command:  wait -n $! >&/dev/null
Location:  ./libparallel, line 247
Stack Trace:
    [1] parallel::wait(): ./libparallel, line 247 -> parallel::wait
    [2] parallel::finish(): ./libparallel, line 73 -> parallel::finish
    [3] aws-resource-list(): ./aws-resource-list, line 87 -> aws-resource-list --parallel=20
    [4] main(): ./aws-resource-list, line 1169 -> main

**Comment by fidian** [comment]
What version of Bash are you using?

**Comment by fidian** [comment]
If you don't know how to check, you could run this command:

    echo "$BASH_VERSION"

**Comment by fidian** [comment]
I would love to know what version of Bash you are using and your settings. I was unable to replicate the issue in any 3.x, 4.x, or 5.x version of Bash with the typical settings that I use that cause issues. If it happens again, the problem relates specifically to the `parallel` library, so go here to report it and include your Bash version, what `set` options you have (`echo $-`) and anything else that you can think of to help me replicate the issue. I've even made a test script in that project that should aid with debugging.

Closing due to no response and lack of information.
